### ISSUE TITLE
renaming cli tool

### ISSUE THREAD

**Issue by NoeelMoeskops** [stephendpmurphy/mpsse-cli#8]
I was thinking that this tool would be pretty handy for a lot of people. So when people use it to try out a new spi/i2c/whatever device they will use the cli frequently. So I think it is important to make it as easy as possible. I was wondering if typing `mpsse-cli` into the terminal is maybe a bit to long, and the `cli` part is redundant since its already clear it's a cli tool since your typing it in the terminal. Just like website having a www.example-site.com. The "site" part unnecessary since its already clear it's a website. I hope you get what I am saying. The current name is however very clear in its purpose and need little explaining.

I was maybe thinking something like just "ft" (because it works with FTdi chips) that would be very quick to type in the terminal
```
# ft spi -c 0 -x w -l 8 -d 0xDD,0xEE,0xAA,0xDD,0xBB,0xEE,0xEE,0xFF
```
instead of:
```
# mpsse-cli spi -c 0 -x w -l 8 -d 0xDD,0xEE,0xAA,0xDD,0xBB,0xEE,0xEE,0xFF
```
What are your thought? Are you open to the idea of changing it? The repo and application can keep the same name, only the binary needs change. We could also do something like `mpsse` or `ftdi`, but I think the shorter the command the better :).

**Comment by stephendpmurphy** [comment]
I would agree, let's change it to ```mpsse```. Feel free to tackle this is you'd like.
